//ex. export const LOGIN_API_REQUEST = 'LOGIN_API_REQUEST';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const RESET_LOGIN = "RESET_LOGIN";

export const CONFIRM_OTP_REQUEST = "CONFIRM_OTP_REQUEST";
export const CONFIRM_OTP_SUCCESS = "CONFIRM_OTP_SUCCESS";
export const CONFIRM_OTP_FAIL = "CONFIRM_OTP_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const INSPECTION_LISTS_REQUEST = "INSPECTION_LISTS_REQUEST";
export const INSPECTION_LISTS_SUCCESS = "INSPECTION_LISTS_SUCCESS";
export const INSPECTION_LISTS_FAIL = "INSPECTION_LISTS_FAIL";

export const PROFILE_DATA_REQUEST = "PROFILE_DATA_REQUEST";
export const PROFILE_DATA_SUCCESS = "PROFILE_DATA_SUCCESS";
export const PROFILE_DATA_FAIL = "PROFILE_DATA_FAIL";

export const GET_TEAMSLIST_REQUEST = "GET_TEAMSLIST_REQUEST";
export const GET_TEAMSLIST_SUCCESS = "GET_TEAMSLIST_SUCCESS";
export const GET_TEAMSLIST_FAIL = "GET_TEAMSLIST_FAIL";

export const DELETE_INSPECTION_REQUEST = "DELETE_INSPECTION_REQUEST";
export const DELETE_INSPECTION_SUCCESS = "DELETE_INSPECTION_SUCCESS";
export const DELETE_INSPECTION_FAIL = "DELETE_INSPECTION_FAIL";

export const GET_INSPECTION_DETAIL_REQUEST = "GET_INSPECTION_DETAIL_REQUEST";
export const GET_INSPECTION_DETAIL_SUCCESS = "GET_INSPECTION_DETAIL_SUCCESS";
export const GET_INSPECTION_DETAIL_FAIL = "GET_INSPECTION_DETAIL_FAIL";

export const DETELE_TEAM_REQUEST = "DETELE_TEAM_REQUEST";
export const DETELE_TEAM_SUCCESS = "DETELE_TEAM_SUCCESS";
export const DETELE_TEAM_FAIL = "DETELE_TEAM_FAIL";

export const GET_CONSUMER_VEHICAL_LIST_REQUEST =
  "GET_CONSUMER_VEHICAL_LIST_REQUEST";
export const GET_CONSUMER_VEHICAL_LIST_SUCCESS =
  "GET_CONSUMER_VEHICAL_LIST_SUCCESS";
export const GET_CONSUMER_VEHICAL_LIST_FAIL = "GET_CONSUMER_VEHICAL_LIST_FAIL";

export const GET_LIST_VEHICLES_REQUEST = "GET_LIST_VEHICLES_REQUEST";
export const GET_LIST_VEHICLES_SUCCESS = "GET_LIST_VEHICLES_SUCCESS";
export const GET_LIST_VEHICLES_FAIL = "GET_LIST_VEHICLES_FAIL";

export const DELETE_LIST_VEHICLE_REQUEST = "DELETE_LIST_VEHICLE_REQUEST";
export const DELETE_LIST_VEHICLE_SUCCESS = "DELETE_LIST_VEHICLE_SUCCESS";
export const DELETE_LIST_VEHICLE_FAIL = "DELETE_LIST_VEHICLE_FAIL";

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_USER_ALL_VEHICLE = "GET_USER_ALL_VEHICLE";
